#!/bin/bash

echo "IP, please?"
read IP

expression='^[0-9]+$'

ping_test(){
    ((count = 1))
    
    while [[ $count -ne 0 ]] ; do
        ping -q -c 1 $IP < /dev/null &> /dev/null
        rc=$?
        if [[ $rc -eq 0 ]] ; then
		((count = 1))
	fi
	((count = count - 1))
    done
}

if [[ $IP =~ $expression ]] ; then
    echo "Please use a valid IP address!"
    exit 1
else
    curl -s ipinfo.io/$IP/json 
    echo
    echo "Checking for Ping..."

    ping_test
    
    if [[ $rc -eq 0 ]] ; then
        echo
	echo "This IP is pingable!"
    else
	echo
	echo "This IP is not pingable!"
    fi
fi 
